spring:
  datasource:                                     #设置数据源信息
    type: com.alibaba.druid.pool.DruidDataSource  #设置数据库连接池的类型
    driver-class-name: org.gjt.mm.mysql.Driver    #设置数据库的驱动
    url: jdbc:mysql://127.0.0.1:3306/training_project?characterEncoding=utf-8        #设置数据库url
    username: root
    password: root
    dbcp2:
      min-idle: 5                               #设置最小连接数
      initial-size: 5                           #设置数据库连接池启动时，创建的连接数
      max-total: 10                             #设置最大连接数
      max-wait-millis: 2000                     #设置最大等待时间
      
mybatis:
  mapper-locations:
  - classpath:mapper/*.xml                      #设置Mybatis的Mapper.xml文件的位置
  type-aliases-package: com.springcloud.entity  #设置 Mybatis实体类位置
  configuration:
    map-underscore-to-camel-case: true          #开动Mybatis驼峰命名规则
